# Generated by Django 2.1.3 on 2018-12-23 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_text', models.CharField(max_length=200)),
                ('pa_result', models.CharField(choices=[('1B', 'Single'), ('2B', 'Double'), ('3B', 'Triple'), ('HR', 'Home Run'), ('G', 'Ground Out'), ('L', 'Line Out'), ('F', 'Fly Out'), ('E', 'Error'), ('K', 'Strike Out'), ('BB', 'Walk'), ('HBP', 'Hit By Pitch')], max_length=3)),
                ('batted_ball_location', models.CharField(choices=[('P', 'Pitcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('LC', 'Left Center'), ('RC', 'Right Center'), ('LS', 'Left Side'), ('M', 'Middle'), ('RS', 'Right Side')], max_length=2)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbpdata.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('tbc_player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pitcher_handedness', models.CharField(choices=[('LEFT', 'Left'), ('SWITCH', 'Switch'), ('RIGHT', 'Right')], max_length=1)),
                ('batter_handedness', models.CharField(choices=[('LEFT', 'Left'), ('SWITCH', 'Switch'), ('RIGHT', 'Right')], max_length=1)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tbc_team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('conference', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbpdata.Team'),
        ),
        migrations.AddField(
            model_name='play',
            name='offense_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbpdata.Team'),
        ),
        migrations.AddField(
            model_name='play',
            name='pitcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbpdata.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='pbpdata.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='pbpdata.Team'),
        ),
    ]
