# Generated by Django 2.1.3 on 2018-12-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbpdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='batted_ball_location',
            field=models.CharField(choices=[('P', 'Pitcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('LC', 'Left Center'), ('RC', 'Right Center'), ('LS', 'Left Side'), ('M', 'Middle'), ('RS', 'Right Side')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='pa_result',
            field=models.CharField(choices=[('1B', 'Single'), ('2B', 'Double'), ('3B', 'Triple'), ('HR', 'Home Run'), ('G', 'Ground Out'), ('L', 'Line Out'), ('F', 'Fly Out'), ('E', 'Error'), ('K', 'Strike Out'), ('BB', 'Walk'), ('HBP', 'Hit By Pitch')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='batter_handedness',
            field=models.CharField(choices=[('LEFT', 'Left'), ('SWITCH', 'Switch'), ('RIGHT', 'Right')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pitcher_handedness',
            field=models.CharField(choices=[('LEFT', 'Left'), ('SWITCH', 'Switch'), ('RIGHT', 'Right')], max_length=1, null=True),
        ),
    ]
