# Generated by Django 2.1.3 on 2018-12-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbpdata', '0002_auto_20181223_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batter_handedness',
            field=models.CharField(choices=[('L', 'Left'), ('S', 'Switch'), ('R', 'Right')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pitcher_handedness',
            field=models.CharField(choices=[('L', 'Left'), ('S', 'Switch'), ('R', 'Right')], max_length=1, null=True),
        ),
    ]
