# Generated by Django 2.1.3 on 2018-12-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbpdata', '0004_auto_20181223_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='batted_ball_location',
            field=models.CharField(choices=[('P', 'Pitcher'), ('1B', 'FirstBase'), ('2B', 'SecondBase'), ('3B', 'ThirdBase'), ('SS', 'Shortstop'), ('LF', 'LeftField'), ('CF', 'CenterField'), ('RF', 'RightField'), ('LC', 'LeftCenter'), ('RC', 'RightCenter'), ('LS', 'LeftSide'), ('M', 'Middle'), ('RS', 'RightSide')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='pa_result',
            field=models.CharField(choices=[('1B', 'Single'), ('2B', 'Double'), ('3B', 'Triple'), ('HR', 'HomeRun'), ('G', 'GroundOut'), ('L', 'LineOut'), ('F', 'FlyOut'), ('E', 'Error'), ('K', 'StrikeOut'), ('BB', 'Walk'), ('HBP', 'HitByPitch')], max_length=25, null=True),
        ),
    ]
