# Generated by Django 2.1.3 on 2018-12-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbpdata', '0005_auto_20181223_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batter_handedness',
            field=models.CharField(choices=[('L', 'Left'), ('S', 'Switch'), ('R', 'Right'), ('U', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pitcher_handedness',
            field=models.CharField(choices=[('L', 'Left'), ('S', 'Switch'), ('R', 'Right'), ('U', 'Unknown')], max_length=10, null=True),
        ),
    ]
